Fix Salesforce CLI installation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,28 +18,39 @@ jobs:
             npm config set prefix '~/.npm-global'
             export PATH=~/.npm-global/bin:$PATH
             echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
-            npm install --global sfdx-cli
-            source $BASH_ENV
+            npm install --global @salesforce/cli
+            exec bash  # Restart shell to apply changes
       - run:
           name: Verify Salesforce CLI Installation
-          command: sfdx --version
+          command: |
+            echo "Current PATH: $PATH"
+            which sf || echo "Salesforce CLI not found!"
+            sf --version || echo "Salesforce CLI version check failed!"
 
   authenticate:
     executor: salesforce-executor
     steps:
       - checkout
       - run:
+          name: Debug PATH and Environment
+          command: |
+            echo "Current PATH: $PATH"
+            ls -la ~/.npm-global/bin
+            echo "BASH_ENV Content:"
+            cat $BASH_ENV
+      - run:
           name: Ensure Salesforce CLI is Available
           command: |
             export PATH=~/.npm-global/bin:$PATH
             source $BASH_ENV
-            sfdx --version
+            which sf || echo "Salesforce CLI not found!"
+            sf --version || echo "Salesforce CLI version check failed!"
       - run:
           name: Authenticate with Salesforce
           command: |
             echo $SFDC_JWT_KEY | base64 --decode > server.key
-            sfdx auth:jwt:grant --client-id $SFDC_CONSUMER_KEY --jwt-key-file server.key --username $SFDC_USERNAME --instance-url https://login.salesforce.com
-            sfdx force:org:list
+            sf org login jwt --client-id $SFDC_CONSUMER_KEY --jwt-key-file server.key --username $SFDC_USERNAME --instance-url https://login.salesforce.com
+            sf org list
 
   create-scratch-org:
     executor: salesforce-executor
@@ -50,19 +61,19 @@ jobs:
           command: |
             export PATH=~/.npm-global/bin:$PATH
             source $BASH_ENV
-            sfdx --version
+            sf --version
       - run:
           name: Create Scratch Org
-          command: sfdx force:org:create -f config/project-scratch-def.json -a CircleCIScratchOrg -d 1 -s
+          command: sf org create scratch -f config/project-scratch-def.json -a CircleCIScratchOrg -d 1 -s
       - run:
           name: Push Source Code
-          command: sfdx force:source:push
+          command: sf project deploy start
       - run:
           name: Run Apex Tests
-          command: sfdx force:apex:test:run --resultformat human --codecoverage --wait 10
+          command: sf apex run test --result-format human --code-coverage --wait 10
       - run:
           name: Delete Scratch Org
-          command: sfdx force:org:delete -u CircleCIScratchOrg -p
+          command: sf org delete scratch -u CircleCIScratchOrg -p
 
   deploy-to-prod:
     executor: salesforce-executor
@@ -73,10 +84,10 @@ jobs:
           command: |
             export PATH=~/.npm-global/bin:$PATH
             source $BASH_ENV
-            sfdx --version
+            sf --version
       - run:
           name: Deploy to Production
-          command: sfdx force:source:deploy -x manifest/package.xml -u $SFDC_USERNAME --wait 10
+          command: sf project deploy start -x manifest/package.xml -o $SFDC_USERNAME --wait 10
 
 workflows:
   version: 2
